### ISSUE TITLE
Component cannot render and give internal error when not using Tailwind

### ISSUE THREAD

**Issue by AristideBH** [bobbymannino/svelte-progress#2]
Hello !
Just tried to use this component on a Sveltekit project without Tailwind, 
and got the following error : 
 ```Cannot find module 'tailwindcss/colors' imported from 'D:/web/noise-fr/node_modules/.pnpm/@bobbymannino+svelte-progress@2.1.1/node_modules/@bobbymannino/svelte-progress/checkTailwindColor.js'```
 
 I also tried to define a custom hex color like so : `<Bar color="#ff0000" />`
 thinking the default value might be tied to Tailwind, but errors are still present.
 
 To reproduce :
 - Start a new Sveltekit project, do not install Tailwind
 - Load the progress components as instructed inside +layout.page
 - Start dev server and check for error in server console.

**Comment by bobbymannino** [comment]
@AristideBH I've had a look at the issue and cannot quite figure it out, I could use a local copy of tailwind's colors but that doesn't seem efficient, do you know of a way to check if tailwind is used in the current users project as I can't seem to find it on google?

**Comment by bobbymannino** [comment]
fixed with a static version if the colors, once I have figured out a better way I will implement it
